version: '3.7'

services:
  app:
    build: .
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_NAME: app
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
